[package]
name = "lithe"
version = "0.1.0"
authors = ["konkers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usb-device = "0.2.5"
usbd-hid = "0.4.4"